version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: northwind_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: northwind
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/schema:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - text2sql_network

  # Optional: Redis for caching (bonus feature)
  redis:
    image: redis:7-alpine
    container_name: text2sql_cache
    ports:
      - "6379:6379"
    networks:
      - text2sql_network

volumes:
  postgres_data:

networks:
  text2sql_network:
    driver: bridge

